eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

server:
  port: 5000

spring:
  application:
    name: eureka-zuul-client

zuul:
  routes:
    ribbonApi:
      path: /ribbon/**
      serviceId: eureka-ribbon-client
    feignApi:
      path: /feign/**
      serviceId: eureka-feign-client